"""Add pack turnover stats

Revision ID: 04c3d7f2f031
Revises: a4faeacb0c11
Create Date: 2026-02-09 10:23:53.124832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c3d7f2f031'
down_revision = 'a4faeacb0c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_turnovers', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_turnover_defenders', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_turnover_midfielders', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_turnover_attackers', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_turnover_score', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###
    
    # Update existing NULL values to 0
    op.execute("UPDATE player_match_stats SET pack_turnovers = 0 WHERE pack_turnovers IS NULL")
    op.execute("UPDATE player_match_stats SET pack_turnover_defenders = 0 WHERE pack_turnover_defenders IS NULL")
    op.execute("UPDATE player_match_stats SET pack_turnover_midfielders = 0 WHERE pack_turnover_midfielders IS NULL")
    op.execute("UPDATE player_match_stats SET pack_turnover_attackers = 0 WHERE pack_turnover_attackers IS NULL")
    op.execute("UPDATE player_match_stats SET pack_turnover_score = 0 WHERE pack_turnover_score IS NULL")
    
    # Make columns non-nullable
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.alter_column('pack_turnovers', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_turnover_defenders', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_turnover_midfielders', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_turnover_attackers', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_turnover_score', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('pack_turnover_score')
        batch_op.drop_column('pack_turnover_attackers')
        batch_op.drop_column('pack_turnover_midfielders')
        batch_op.drop_column('pack_turnover_defenders')
        batch_op.drop_column('pack_turnovers')

    # ### end Alembic commands ###
