"""Replace passing stats with short and long pass variants

Revision ID: 4fc74a475eb2
Revises: a30e476c99e2
Create Date: 2026-02-09 08:59:14.754807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc74a475eb2'
down_revision = 'a30e476c99e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_completed_passes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('short_incomplete_passes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('long_completed_passes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('long_incomplete_passes', sa.Integer(), nullable=True))
        batch_op.drop_column('incomplete_passes')
        batch_op.drop_column('completed_passes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_passes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('incomplete_passes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('long_incomplete_passes')
        batch_op.drop_column('long_completed_passes')
        batch_op.drop_column('short_incomplete_passes')
        batch_op.drop_column('short_completed_passes')

    # ### end Alembic commands ###
