"""Add pack pass stats and pack pass score

Revision ID: 56092f047881
Revises: b78d276df0a1
Create Date: 2026-02-09 09:55:29.981641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56092f047881'
down_revision = 'b78d276df0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_passes', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_pass_defenders', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_pass_midfielders', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_pass_attackers', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('pack_pass_score', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###
    
    # Update existing NULL values to 0
    op.execute("UPDATE player_match_stats SET pack_passes = 0 WHERE pack_passes IS NULL")
    op.execute("UPDATE player_match_stats SET pack_pass_defenders = 0 WHERE pack_pass_defenders IS NULL")
    op.execute("UPDATE player_match_stats SET pack_pass_midfielders = 0 WHERE pack_pass_midfielders IS NULL")
    op.execute("UPDATE player_match_stats SET pack_pass_attackers = 0 WHERE pack_pass_attackers IS NULL")
    op.execute("UPDATE player_match_stats SET pack_pass_score = 0 WHERE pack_pass_score IS NULL")
    
    # Make columns non-nullable
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.alter_column('pack_passes', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_pass_defenders', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_pass_midfielders', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_pass_attackers', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('pack_pass_score', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('pack_pass_score')
        batch_op.drop_column('pack_pass_attackers')
        batch_op.drop_column('pack_pass_midfielders')
        batch_op.drop_column('pack_pass_defenders')
        batch_op.drop_column('pack_passes')

    # ### end Alembic commands ###
