"""Set goals and assists as not nullable with default 0

Revision ID: 65f422b95243
Revises: 8a327e40cf16
Create Date: 2026-02-09 13:42:32.202689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f422b95243'
down_revision = '8a327e40cf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any NULL values to 0 before setting NOT NULL constraint
    op.execute("UPDATE player_match_stats SET goals = 0 WHERE goals IS NULL")
    op.execute("UPDATE player_match_stats SET assists = 0 WHERE assists IS NULL")
    
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.alter_column('goals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('assists',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.alter_column('assists',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('goals',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
