"""Add surface, formations, remove attendance, add match lineups

Revision ID: 8a327e40cf16
Revises: 6aa941d05856
Create Date: 2026-02-09 11:13:47.213448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a327e40cf16'
down_revision = '6aa941d05856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('home_formation', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('away_formation', sa.String(length=20), nullable=True))
        batch_op.drop_column('attendance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('away_formation')
        batch_op.drop_column('home_formation')
        batch_op.drop_column('surface')

    # ### end Alembic commands ###
