"""Add shots_blocked to PlayerMatchStats

Revision ID: a30e476c99e2
Revises: 
Create Date: 2026-02-09 08:55:53.730116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30e476c99e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shots_blocked', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('shots_blocked')

    # ### end Alembic commands ###
