"""Add pack pass receive score

Revision ID: a4faeacb0c11
Revises: 56092f047881
Create Date: 2026-02-09 10:13:41.629032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4faeacb0c11'
down_revision = '56092f047881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_pass_receive_score', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###
    
    # Update existing NULL values to 0
    op.execute("UPDATE player_match_stats SET pack_pass_receive_score = 0 WHERE pack_pass_receive_score IS NULL")
    
    # Make column non-nullable
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.alter_column('pack_pass_receive_score', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('pack_pass_receive_score')

    # ### end Alembic commands ###
