"""Add crosses, throw-ins, and recoveries stats

Revision ID: b78d276df0a1
Revises: b7f3b250b08a
Create Date: 2026-02-09 09:38:24.443329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78d276df0a1'
down_revision = 'b7f3b250b08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('successful_crosses', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('unsuccessful_crosses', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('throw_in_retained', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('throw_in_lost', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('recoveries', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###
    
    # Update existing NULL values to 0
    op.execute("UPDATE player_match_stats SET successful_crosses = 0 WHERE successful_crosses IS NULL")
    op.execute("UPDATE player_match_stats SET unsuccessful_crosses = 0 WHERE unsuccessful_crosses IS NULL")
    op.execute("UPDATE player_match_stats SET throw_in_retained = 0 WHERE throw_in_retained IS NULL")
    op.execute("UPDATE player_match_stats SET throw_in_lost = 0 WHERE throw_in_lost IS NULL")
    op.execute("UPDATE player_match_stats SET recoveries = 0 WHERE recoveries IS NULL")
    
    # Make columns non-nullable
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.alter_column('successful_crosses', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('unsuccessful_crosses', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('throw_in_retained', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('throw_in_lost', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('recoveries', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('recoveries')
        batch_op.drop_column('throw_in_lost')
        batch_op.drop_column('throw_in_retained')
        batch_op.drop_column('unsuccessful_crosses')
        batch_op.drop_column('successful_crosses')

    # ### end Alembic commands ###
